version: '3'

services:
  djangoapp:
    container_name: djangoapp
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    # networks:
    #   - reservoir_network

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    # build:
    #   context: .
    #   dockerfile: Dockerfile.postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    # networks:
    #   - reservoir_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    # networks:
    #   - reservoir_network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - djangoapp
    # networks:
    #   - reservoir_network

volumes:
  pgdata:


# networks:
#   reservoir_network:
#     driver: bridge


