# Generated by Django 4.1.4 on 2023-07-02 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastTestingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=500, null=True)),
                ('actor_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowMoviesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTestingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('coverImgUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressMoviesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTestingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMoviesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='movieApp.movietestingmodel')),
            ],
        ),
    ]
