# Generated by Django 4.1.4 on 2023-07-02 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmoviesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roletestingmodel',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movieApp.casttestingmodel'),
        ),
        migrations.AddField(
            model_name='roletestingmodel',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movieApp.movietestingmodel'),
        ),
        migrations.AddField(
            model_name='progressmoviesmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.movietestingmodel'),
        ),
        migrations.AddField(
            model_name='progressmoviesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movietestingmodel',
            index=models.Index(fields=['id'], name='movieApp_mo_id_1d7e39_idx'),
        ),
        migrations.AddField(
            model_name='movielistmodel',
            name='movie',
            field=models.ManyToManyField(to='movieApp.movietestingmodel'),
        ),
        migrations.AddField(
            model_name='movielistmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followmoviesmodel',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_movie', to='movieApp.movietestingmodel'),
        ),
        migrations.AddField(
            model_name='followmoviesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedmoviesmodel',
            unique_together={('movie_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='progressmoviesmodel',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='followmoviesmodel',
            unique_together={('movie_name', 'user')},
        ),
    ]
