# Generated by Django 4.1.4 on 2023-07-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietestingmodel',
            name='userHasCover',
            field=models.BooleanField(default=False),
        ),
    ]
