# Generated by Django 4.1.4 on 2023-07-04 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_movietestingmodel_userhascover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietestingmodel',
            name='userHasCover',
        ),
        migrations.CreateModel(
            name='MovieUserHasCover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userHasCover', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.movietestingmodel')),
            ],
        ),
    ]
