# Generated by Django 4.1.4 on 2023-07-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_remove_movietestingmodel_userhascover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieuserhascover',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieApp.movietestingmodel'),
        ),
    ]
