# Generated by Django 4.1.4 on 2023-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_alter_movieuserhascover_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietestingmodel',
            name='userHasCover',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MovieUserHasCover',
        ),
    ]
